# Generated by Django 6.1.1 on 2026-09-28 03:35

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('nb_risk', '0011_vulnerability_epss_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpemapping',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.RemoveField(
            model_name='cpemapping',
            name='tags',
        ),
        migrations.AddField(
            model_name='cpemapping',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
